In [ ]:
import os
import sys
os.chdir('/home/peitian_zhang/Codes/NR')
sys.path.append('/home/peitian_zhang/Codes/NR')

In [14]:
import torch
import torch.nn.functional as F
a = torch.tensor([[[1,2,3,4],[2,2,3,4],[4,2,3,4]],[[3,2,3,4],[0,0,0,0],[0,0,0,0]]]).float()
b = torch.tensor([[[4,2,3,4],[5,2,3,4],[0,0,0,0]],[[6,2,3,4],[7,2,3,4],[8,2,3,4]]]).float().permute(0,2,1)

sim = torch.bmm(F.normalize(a),F.normalize(b)).view(2, 3, 3, 1)
mu = torch.tensor((1,2,3,6)).float().view(1,1,1,4)
sigma = torch.tensor((4,3,2,1)).float().view(1,1,1,4)

mask_q = torch.tensor([[1,1,1],[1,0,0]]).float().view(2,3,1)
mask_d = torch.tensor([[1,1,0],[1,1,1]]).float().view(2,1,3,1)
r = (sim - mu)
k = r/sigma # 2,3,3,4
k_plus = k * mask_d
u = torch.sum(k_plus,dim=2)
u_plus = u*mask_q

result = torch.sum(u_plus,dim=-2)
# u, mask_d
sim, k, k_plus, u, u_plus, result

(tensor([[[[0.9047],
           [0.8556],
           [0.0000]],
 
          [[1.0348],
           [1.0041],
           [0.0000]],
 
          [[1.2951],
           [1.3010],
           [0.0000]]],
 
 
         [[[1.8605],
           [1.8116],
           [1.7628]],
 
          [[0.0000],
           [0.0000],
           [0.0000]],
 
          [[0.0000],
           [0.0000],
           [0.0000]]]]),
 tensor([[[[-2.3821e-02, -3.6509e-01, -1.0476e+00, -5.0953e+00],
           [-3.6104e-02, -3.8147e-01, -1.0722e+00, -5.1444e+00],
           [-2.5000e-01, -6.6667e-01, -1.5000e+00, -6.0000e+00]],
 
          [[ 8.7092e-03, -3.2172e-01, -9.8258e-01, -4.9652e+00],
           [ 1.0159e-03, -3.3198e-01, -9.9797e-01, -4.9959e+00],
           [-2.5000e-01, -6.6667e-01, -1.5000e+00, -6.0000e+00]],
 
          [[ 7.3769e-02, -2.3497e-01, -8.5246e-01, -4.7049e+00],
           [ 7.5255e-02, -2.3299e-01, -8.4949e-01, -4.6990e+00],
           [-2.5000e-01, -6.6667e-01, -1.5000e+00, -6.0000e+00]]],
 
 
   

In [10]:
import torch.nn.functional as F
import torch
import math
F.normalize(torch.tensor([[1,2,3,4]]).float(), p=2)

(tensor([[0.1826, 0.3651, 0.5477, 0.7303]]), 0.7302967433402214)

In [ ]:
import torch
a = torch.nn.Softmax(dim=-1)
b = torch.rand((2,3,3))
a(b)
torch.sum(a(b),dim=-1)

In [ ]:
a = [torch.rand((1,2)) for _ in range(3)]
a = torch.rand((1,2))
a  = torch.rand((1,2,3))
a,a.transpose(-1,0)

In [ ]:
b, torch.sum(torch.log(b),dim=1)


In [ ]:
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter('data/test')

In [ ]:
import torch
writer.add_embedding(torch.rand((5,5)),meta)

In [3]:
import torch
import torch.nn.functional as F

a = torch.tensor([[1,2,3]]).float()
b = torch.tensor([[2,3,4]]).float()
c = F.normalize(a)
d = F.normalize(b)
torch.matmul(c,d.permute(1,0))

tensor([[0.9926]])