In [1]:
import os
import sys
os.chdir('/home/peitian_zhang/Codes/NR')
sys.path.append('/home/peitian_zhang/Codes/NR')

In [2]:
t = torch.tensor([[[1.,0.5,0.],[0.5,0,1]],[[0.5,0,1],[1,0.5,0]]])
a,b = knrm._kernel_pooling(t)

tensor([[[0.6065, 1.0000, 0.6069, 0.0000],
         [0.6065, 1.0000, 0.6069, 0.0000]],

        [[0.6065, 1.0000, 0.6069, 0.0000],
         [0.6065, 1.0000, 0.6069, 0.0000]]])


In [2]:
import torch
a = torch.nn.Softmax(dim=-1)
b = torch.rand((2,3,3))
a(b)
torch.sum(a(b),dim=-1)

tensor([[1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000]])

In [14]:
a = [torch.rand((1,2)) for _ in range(3)]
a = torch.rand((1,2))
a  = torch.rand((1,2,3))
a,a.transpose(-1,0)

(tensor([[[0.7002, 0.9531, 0.7439],
          [0.4457, 0.5116, 0.6311]]]),
 tensor([[[0.7002],
          [0.4457]],
 
         [[0.9531],
          [0.5116]],
 
         [[0.7439],
          [0.6311]]]))

In [6]:
b, torch.sum(torch.log(b),dim=1)


(tensor([[0.6069, 0.6069],
         [0.6069, 0.6069]]),
 tensor([-0.9989, -0.9989]))

In [2]:
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter('data/test')

In [5]:
import torch
writer.add_embedding(torch.rand((5,5)),meta)