In [2]:
import torch

### repeating samples along axis

*repeat_interleave* is equal to *cat and view*

In [3]:
a =torch.tensor([[[1,2]],[[2,3]]])
print(a,a.shape)

a.repeat_interleave(repeats=2,dim=0),torch.cat([a.unsqueeze(dim=1)]*2,dim=1).view(-1,1,2)

tensor([[[1, 2]],

        [[2, 3]]]) torch.Size([2, 1, 2])


(tensor([[[1, 2]],
 
         [[1, 2]],
 
         [[2, 3]],
 
         [[2, 3]]]),
 tensor([[[1, 2]],
 
         [[1, 2]],
 
         [[2, 3]],
 
         [[2, 3]]]))

### understanding *permute*

let's suppose there is a tensor of $[dim0, dim1, dim2, dim3]$, then we permute it to $[dim3, dim1, dim2, dim0]$,
    - **consequence**: origin value at $[a, b, c, d]$ will be switched to $[d, b, c, a]$

In [ ]:
a = torch.zeros([5,4,3,2]),
# say a=2, b=3, c=1, d=1,
a[2,3,1,1] = 1,
print("origin 1 at [2,3,1,1]: {}".format(a[2,3,1,1])),
b = a.permute(3,1,2,0),
print("permuted 1 at [3,1,2,0]: {}".format(b[1,3,1,2]))

### torch.autograd
Only when the operation in the forward phrase is **not differentiable** while you want the gradient to be pass through that you should rewrite torch.autograd, where you can define your own backward algorithm to give an approximate gradient of the **indifferentiable** operation.