In [8]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchtext.vocab import GloVe
from utils.preprocess import MINDIterator
from utils.utils import getVocab,getLoss,getLabel,constructBasicDict
from utils.utils import run_eval
from torchtext.data.utils import get_tokenizer
from torchtext.data import Dataset
from torchtext.vocab import build_vocab_from_iterator

In [4]:
conv = nn.Conv1d(kernel_size=3,in_channels=2,out_channels=2,dilation=1,padding=1)
a = torch.zeros((1,2,5))
a_ = torch.zeros((1,2,5))
a = torch.cat([a,a_],dim=2)

In [42]:
a = [0,1,2]
a[:5] + [0] * (5-len(a))

[0, 1, 2, 0, 0]

In [28]:
input_ = torch.tensor([[[1,2],[6,3]],[[3,4],[4,5]]],dtype=torch.float)
# With Learnable Parameters
m1 = nn.LayerNorm(input_.size()[1])
# Without Learnable Parameters
m2 = nn.LayerNorm(input_.size()[1:], elementwise_affine=False)
# Normalize over last two dimensions
# m3 = nn.LayerNorm([2,2])
 # Normalize over last dimension of size 10
# m4 = nn.LayerNorm(5)
output1 = m1(input_)
output2 = m2(input_)
# output3 = m3(input_)
# output4 = m4(input_)
input_,output1,output2#,output3,output4

(tensor([[[1., 2.],
          [6., 3.]],
 
         [[3., 4.],
          [4., 5.]]]),
 tensor([[[-1.0000,  1.0000],
          [ 1.0000, -1.0000]],
 
         [[-1.0000,  1.0000],
          [-1.0000,  1.0000]]], grad_fn=<NativeLayerNormBackward>),
 tensor([[[-1.0690, -0.5345],
          [ 1.6036,  0.0000]],
 
         [[-1.4142,  0.0000],
          [ 0.0000,  1.4142]]]))

In [25]:
input_.size()[1:2]

torch.Size([2])

In [1]:
import pandas as pd

news_file = r'D:\Data\NR_data\dev\news.tsv'

news_df = pd.read_table(news_file,index_col=None,names=['newsID','category','subcategory','title','abstract','url','entity_title','entity_abstract'])

In [7]:
news_df.iloc[-1,:]
vocab['autos']

NameError: name 'vocab' is not defined

In [16]:
count = 0
a = []
tokenizer = get_tokenizer('basic_english')
news_iterator = news_df.iterrows()
for _,i in news_iterator:
    if count > 10:
        break
    content = []
    for attr in ['title','category']:
        content.append(i[attr])
    count += 1
    yield tokenizer(' '.join(content))

SyntaxError: 'yield' outside function (<ipython-input-16-b9d96439f9e8>, line 12)

In [17]:
import numpy as np
np.array([[1,2],[1,2,3]])

array([list([1, 2]), list([1, 2, 3])], dtype=object)

In [18]:
tokenizer

<function torchtext.data.utils._basic_english_normalize(line)>

In [31]:
def news_token_generator_group(news_file,tokenizer,mode):
    ''' iterate news_file, collect attrs and generate them respectively
       
    Args: 
        tokenizer: torchtext.data.utils.tokenizer
        mode: int defining how many attributes to be generated
    Returns: 
        a generator over attrs in news
    '''
    news_df = pd.read_table(news_file,index_col=None,names=['newsID','category','subcategory','title','abstract','url','entity_title','entity_abstract'])
    news_iterator = news_df.iterrows()
    
    attrs = ['title','category','subcategory','abstract']
    for _,i in news_iterator:
        result = []
        indicate = 0
        while indicate < mode:
            result.append(tokenizer(i[attrs[indicate]]))
            indicate += 1
        yield result 

In [32]:
a = news_token_generator_group(news_file,tokenizer,4)

In [36]:
next(a)

[['i',
  'was',
  'an',
  'nba',
  'wife',
  '.',
  'here',
  "'",
  's',
  'how',
  'it',
  'affected',
  'my',
  'mental',
  'health',
  '.'],
 ['health'],
 ['voices'],
 ['i',
  'felt',
  'like',
  'i',
  'was',
  'a',
  'fraud',
  ',',
  'and',
  'being',
  'an',
  'nba',
  'wife',
  'didn',
  "'",
  't',
  'help',
  'that',
  '.',
  'in',
  'fact',
  ',',
  'it',
  'nearly',
  'destroyed',
  'me',
  '.']]