In [ ]:
from utils.utils import constructBasicDict
from utils.preprocess import MINDIterator

define paths and hyperparameters

*title_size*: max word capacity of title

*his_size*: max record capacity of click history


In [ ]:
news_file = r'D:\Data\NR_data\MINDsmall_train\news.tsv'
behavior_file = r'D:\Data\NR_data\MINDsmall_train\behaviors.tsv'
hparams = {
    'batch_size':10,
    'title_size':20,
    'his_size':20,
    'npratio':3,
    'mode':'small'
}

construct basic dictionaries, such as *newsID2newsINDEX, userID2userINDEX, Vocabulary*

only need to run once

In [ ]:
constructBasicDict(news_file,behavior_file,'small')

instantiate MINDIterator

In [ ]:
k = MINDIterator(hparams=hparams)
train = k.load_data_from_file(news_file,behavior_file)

In [ ]:
a = next(train)

In [1]:
import torch

In [24]:
a = torch.tensor([[1,0,0,0],[0,1,0,0],[0,0,1,0],[1,0,0,1]])
b = torch.arange(0,4).expand(4,-1)

In [27]:
c = a==1#,b[a==1]
c

tensor([[ True, False, False, False],
        [False,  True, False, False],
        [False, False,  True, False],
        [ True, False, False,  True]])

In [32]:
b[c]

tensor([0, 1, 2, 0, 3])

In [39]:
d = torch.tensor([[0],[1],[0]],dtype=torch.float32)
e = torch.tensor([[0.5],[0.9],[0.2]])

In [40]:
loss = torch.nn.BCELoss()
loss(e,d)

tensor(0.3406)

In [1]:
from utils.utils import getTrain,getLabel
import torch

In [2]:
class model():
    npratio = 3
    batch_size = 5

In [3]:
a = model()

In [4]:
loss = getTrain(a)

In [6]:
label = getLabel(a,{'labels':torch.tensor([[1,0,0,0],[0,1,0,0],[0,0,1,0],[1,0,0,0],[0,0,0,1]])})

In [7]:
label

tensor([0, 1, 2, 0, 3])